version: '3.9'

services:
  waha:
    build: .
    container_name: waha-server
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
